# Generated by Django 5.1 on 2026-06-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='auto_tags',
            field=models.JSONField(blank=True, default=None, help_text='AI-generated tags from image analysis', null=True),
        ),
    ]
